apiVersion: v1
kind: Namespace
metadata:
  name: n8n-provisioning
---
apiVersion: v1
kind: Secret
metadata:
  name: provision-secrets
  namespace: n8n-provisioning
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://akaneai420:ilovehentai321@cluster0.jwyab3g.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  DOMAIN_NAME: "173956.xyz"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: n8n-provisioner
  namespace: n8n-provisioning
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: n8n-provisioner
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods", "services", "persistentvolumeclaims"]
  verbs: ["get", "list", "create", "delete", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: n8n-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: n8n-provisioner
subjects:
- kind: ServiceAccount
  name: n8n-provisioner
  namespace: n8n-provisioning
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-provisioner
  namespace: n8n-provisioning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n-provisioner
  template:
    metadata:
      labels:
        app: n8n-provisioner
    spec:
      serviceAccountName: n8n-provisioner
      containers:
      - name: provisioner
        image: 5quidw4rd/n8n-provisioner:latest
        ports:
        - containerPort: 9000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: provision-secrets
              key: MONGODB_URI
        - name: DOMAIN_NAME
          valueFrom:
            secretKeyRef:
              name: provision-secrets
              key: DOMAIN_NAME
        livenessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: n8n-provisioner
  namespace: n8n-provisioning
spec:
  selector:
    app: n8n-provisioner
  ports:
  - port: 80
    targetPort: 9000
  type: LoadBalancer
